name: myapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  syncfusion_flutter_pdfviewer: ^23.2.7
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.6
  youtube_player_flutter: ^8.1.2
  flutter_inappwebview: ^5.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/fox.png

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: lib/fonts/NotoSansSC-Light.ttf
